### ISSUE TITLE
Gradebook - column text and sorting doesn't fit the column

### ISSUE THREAD

**Issue by ppv1979** [gjb2048/moodle-theme_essential#189]
In the header of grade book table icon in right column overlaps sorting icons and text in the left column. 
![2014-08-21 22 48 08](https://cloud.githubusercontent.com/assets/5909987/3999757/495fca98-2953-11e4-9096-e827f764f6e4.png)

I think this problem is similar with mentioned trouble in fix for #175.

``` css
/* Improve wrapping around user picture */ 
.path-grade-report-grader th.user img.userpicture {
   float: left;
}
```

This code breaks the cells with users in non-fixed column view in the same manner.
