### ISSUE TITLE
Gradebook - vertical size in fixed column view

### ISSUE THREAD

**Issue by ppv1979** [gjb2048/moodle-theme_essential#196]
In fixed column view the rows can have different heights in left and right scroller.
![2014-08-23 21 16 51](https://cloud.githubusercontent.com/assets/5909987/4020928/aa76d9a2-2ad9-11e4-8ddf-a36d5c165967.png)

Solution:

``` css
/* Wrap image */ 
.path-grade-report-grader th.user img.userpicture {
   float: left;
}
.path-grade-report-grader #user-grades th.user {
  padding-right: 45px;
}
```

Second rule is needed for non-fixed column view, because of problem that is similar to the bug described in #189 

Result:
![2014-08-23 21 19 42](https://cloud.githubusercontent.com/assets/5909987/4020932/18255fe6-2ada-11e4-87b5-c908d3bad64d.png)
